export default {
  FormFieldLabel: () => import('./FormFieldLabel.vue'),
  FormFieldInput: () => import('./FormFieldInput.vue'),
  FormFieldSelect: () => import('./FormFieldSelect.vue'),
  FormFieldCascade: () => import('./FormFieldCascade.vue'),
  FormFieldColor: () => import('./FormFieldColor.vue'),
  FormFieldRadio: () => import('./FormFieldRadio.vue'),
  FormFieldCheckbox: () => import('./FormFieldCheckbox.vue'),
  FormFieldImage: () => import('./FormFieldImage.vue'),
  FormFieldUpload: () => import('./FormFieldUpload.vue'),
  FormFieldEditor: () => import('./FormFieldEditor.vue'),
  FormFieldGallery: () => import('./FormFieldGallery.vue'),
  FormFieldNumber: () => import('./FormFieldNumber.vue'),
  FormFieldSwitch: () => import('./FormFieldSwitch.vue'),
  FormFieldRate: () => import('./FormFieldRate.vue'),
  FormFieldDate: () => import('./FormFieldDate.vue'),
  FormFieldObject: () => import('./FormFieldObject.vue'),
  FormFieldMultiObject: () => import('./FormFieldMultiObject.vue'),
  FormFieldDistrict: () => import('./FormFieldDistrict.vue'),
  FormFieldListView: () => import('./FormFieldListView.vue'),
  FormFieldRender: () => import('./FormFieldRender.vue'),
  FormFieldMap: () => import('./FormFieldMap.vue')
}
